---
title: "Publications"
#jupyter: python3
---

### 2026

Montalvo Puente C. E., Lago G., **Cardarelli L.**, Costantine-Castro J., Pérez Molina J., Counting rather than weighing: metrological analysis and machine learning reveal the monetary potential of pre-contact Ecuadorian axe-monies. *Journal of Archaeological Science: Reports*, 69   [{{< fa file title="Link" >}}](https://www.sciencedirect.com/science/article/pii/S2352409X25005589)

### 2025

**Cardarelli L.**, PyPotteryInk: One-step diffusion model for sketch to publication-ready archaeological drawings. *Journal of Cultural Heritage*, 74  [{{< fa file title="Link" >}}](https://www.sciencedirect.com/science/article/pii/S1296207425001268)

Carletti E., Conati Barbaro C., Allegretta I., **Cardarelli L.**, Forti L., Monno A., Terzano R., Eramo G., Chert sources and territorial behaviour after the Neolithization process: An exploratory analysis from Grotta Battifratta (Rieti, Central Italy). *Quaternary International*, 717   [{{< fa file title="Link" >}}](https://doi.org/10.1016/j.quaint.2024.109633)

**Cardarelli L.**, The legacy: the Data Science movement. *Analyse des données and archaeology fifty years later: from data analysis to data science*, All’Insegna del Giglio [{{< fa file title="Link" >}}](https://www.insegnadelgiglio.it/wp-content/uploads/2025/06/9788892853751.pdf)


**Cardarelli L.**, Fragnoli P., D'Anna M. B., Quantifying morphological standardization through binary matrices with an application to the ceramic assemblage of an early complex society. *Paléorient.*, 51 [{{< fa file title="Link" >}}](https://journals.openedition.org/paleorient/5687)


**Cardarelli L.**, PyPotteryLens: An Open-Source Deep Learning Framework for Automated Digitisation of Archaeological Pottery Documentation. *Digital Applications in Archaeology and Cultural Heritage*, 38 [{{< fa file title="Link" >}}](https://www.sciencedirect.com/science/article/pii/S2212054825000542)

Alessandri L., **Cardarelli L.**, Cesaretti A., Dan R., Fiorillo A., Sotgia A., Cusimano L., Della sala G. A., Rossi C., From pencil to pixel: assessing ceramatic 2.0 against manual and laser-aided techniques in archaeological pottery documentation. *Digital Applications in Archaeology and Cultural Heritage*, 37 [{{< fa file title="Link" >}}](https://www.sciencedirect.com/science/article/pii/S2212054825000372)

**Cardarelli L.**, PyPotteryInk: One-Step Diffusion Model for Sketch to Publication-ready Archaeological Drawings, *preprint*   [{{< fa file title="Link" >}}](https://arxiv.org/abs/2502.06897)   [{{< fa code title="Link" >}}](https://github.com/lrncrd/PyPotteryInk)

### 2024


**Cardarelli L.**, PyPotteryLens: An Open-Source Deep Learning Framework for Automated Digitisation of Archaeological Pottery Documentation, *preprint*   [{{< fa file title="Link" >}}](https://arxiv.org/abs/2412.11574)   [{{< fa code title="Link" >}}](https://github.com/lrncrd/PyPottery/tree/PyPotteryLens)

**Cardarelli L.**, Erbetti F., Paniccia C., Paolini E., Vessel typological classification: comparing archaeologist perspectives to a digital approach. *Studi in onore di Andrea Cardarelli*, Naus Editoria

**Cardarelli L.**, Morphological variability and standardisation of vessel shapes in the 2nd and first half of the first millennium BC in continental Italy. A data science and machine learning project for the quantitative study of archaeological ceramic profiles. Edipuglia ISBN 979-12-5995-084-0   [{{< fa file title="Link" >}}](https://edipuglia.it/PDF/index.php?file=Adrias_18&n=Adrias_18&t)   [{{< fa code title="Link" >}}](https://edipuglia.it/pasap01/)

**Cardarelli L.**, From fragments to digital wholeness: an AI generative approach to reconstructing archaeological vessels. *Journal of Cultural Heritage*, 70   [{{< fa file title="Link" >}}](https://doi.org/10.1016/j.culher.2024.09.012)   [{{< fa code title="Link" >}}](https://github.com/lrncrd/ReconstructionPots)

Lago G., **Cardarelli L.**, Ialongo N., Cqarchaeo: a Python package for cosine quantogram analysis and Monte Carlo simulations. *Archeologia e Calcolatori*, 35.1   [{{< fa file title="Link" >}}](https://doi.org/10.19282/ac.35.1.2024.15)   [{{< fa code title="Link" >}}](https://github.com/lrncrd/CQArchaeo)

### 2023

Cardarelli A., Di Renzoni A., Bettelli M., de Neef W., Scacchetti F., **Cardarelli L.**, Paniccia C., Paolini E., The Late Bronze age hilltop site of Monte Croce Guardia in the context of Bronze Age and Early Iron Age settlement organization in Peninsular Italy. *Origini*, XLVII   [{{< fa file title="Link" >}}](https://www.torrossa.com/it/catalog/preview/5751207)

**Cardarelli L.**, Traditional and digital typologies compared: the example of Italian protohistory. *Origini*, XLVII   [{{< fa file title="Link" >}}](https://www.torrossa.com/it/catalog/preview/5751207)   [{{< fa code title="Link" >}}](https://www.edizioniquasar.cloud/Typologies-traditional-vs-digital/)

**Cardarelli L.**, Defining Southern Etruria Final Bronze Age settlement models using an integrated GIS and machine learning approach. *Archeologia e Calcolatori*, 34.2   [{{< fa file title="Link" >}}](https://doi.org/10.19282/ac.34.2.2023.03)

Santi P., Cardarelli A., Bettelli M. Di Renzoni A., **Cardarelli L.**, Paniccia C., Renzulli A., Tracing the human movements of three thousand years ago by volcanic grinding tools in the Final Bronze Age settlement of Monte Croce Guardia (Arcevia-Marche Region, central Italy). *Scientific Reports* 13, 7022   [{{< fa file title="Link" >}}](https://www.nature.com/articles/s41598-023-34033-x)

Montalvo Puente C. E., Lago G., **Cardarelli L.**, Pérez Molina J. C., Money or ingots? Metrological research on pre-contact Ecuadorian "axe-monies". *Journal of Archaeological Science: Reports*, 49   [{{< fa file title="Link" >}}](https://doi.org/10.1016/j.jasrep.2023.103976)

### 2022

**Cardarelli L.**, A deep variational convolutional Autoencoder for unsupervised features extraction of ceramic profiles. A case study from central Italy. *Journal of Archaeological Science*, 144   [{{< fa file title="Link" >}}](https://doi.org/10.1016/j.jas.2022.105640)   [{{< fa code title="Link" >}}](https://github.com/lrncrd/VAEpots)

Montalvo Puente C. E., Lago G., **Cardarelli L.**, Pérez Molina J. C., Money or ingots? Metrological research on pre-contact Ecuadorian 'axe-monies' (*preprint*)   [{{< fa file title="Link" >}}](https://doi.org/10.21203/rs.3.rs-1962271/v1)

**Cardarelli L.**, Lapadula A., Dimensionality reduction for data visualization and exploratory analysis of ceramic assemblages. *Archeologia e Calcolatori*, 33.2   [{{< fa file title="Link" >}}](https://doi.org/10.19282/ac.33.2.2022.03)   [{{< fa file-pdf title="Link" >}}](http://www.archcalc.cnr.it/indice/PDF33.2/03_Cardarelli_Lapadula.pdf)

### 2020

**Cardarelli L.**, Capienza delle forme vascolari, da un metodo open source all'uso di modelli regressivi: il caso dell'insediamento protostorico del Monte Cimino. *Archeologia e Calcolatori*, 31.1   [{{< fa file title="Link" >}}](https://doi.org/10.19282/ac.31.1.2020.02)   [{{< fa file-pdf title="Link" >}}](http://www.archcalc.cnr.it/indice/PDF31.1/02_Cardarelli.pdf)