---
title: "Conference Talks"
---

### 2024

30^th^ EAA annual meeting. **Cardarelli L.**, New perspective in quantitative archaeology: data driven approaches in pottery analysis. Rome, 28^th^ - 31^th^ August 2024.

30^th^ EAA annual meeting. Carletti E., Eramo G., **Cardarelli L.**, Forti L., Allegretta I., Monno A., Conati Barbaro C., New directions in chert provenance: towards new basis for detecting mobility ad territorial behaviour in central Italy during prehistory. Rome, 28^th^ - 31^th^ August 2024.

30^th^ EAA annual meeting. Lara C., **Cardarelli L.**, Lago G., Montalvo C., Tacconi S., Costantine A., Presentation of the project "Southern Ecuador and Northern Peru as an Andrean interface (AD 500-1532)". Rome, 28^th^ - 31^th^ August 2024.

### 2023

Conversation - Museo Numismatico, Banco Central del Ecuador. Montalvo Puente C. E., Lago G., **Cardarelli L.**, Pérez Molina J. C., Avances sobre los estudios de las hachas-monedasQuito (ECU), 23 July 2023.

13° International Congress on the Archaeology of the Ancient Near East (ICAANE). Workshop Serialising, standardising, specialising: Investigating a techno-social nexus underlying social complexity. **Cardarelli L.**, Computerised approaches for investigating the morphological standardization of Arslantepe VI A pottery, Copenhagen, 24 may 2023

### 2020

IAS -- Incontri di Archeologia 2020. Digital Humanities Session I-II. **Cardarelli L.**, Capienza delle forme vascolari, un metodo basato su strumenti e formati open source che include l'uso di modelli regressivi: il caso dell'insediamento protostorico del Monte Cimino (paper). Rome, 19 november 2020.
